name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FuseSoC and Black Formatter
        run: |
          pip install git+https://github.com/x-heep/fusesoc.git@ot#egg=fusesoc black

      - name: Install Verible
        run: |
          VERIBLE_VERSION=v0.0-4023-gc1271a00
          URL="https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-linux-static-x86_64.tar.gz"
          wget "$URL" -q -O verible.tar.gz
          mkdir -p verible-bin
          tar -xzf verible.tar.gz -C verible-bin --strip-components=1
          echo "$GITHUB_WORKSPACE/verible-bin/bin" >> $GITHUB_PATH

      - name: Run Linting
        run: make lint

      - name: Run Formatting
        run: make format

      - name: Check Formatting
        run: |
          if ! git diff --exit-code; then
            echo "Error: Files were modified after running 'make format'."
            echo "Please run 'make format' locally and commit the changes."
            exit 1
          fi
